---
title: Kitchen Wall App
author: AP Studio, LLC
email: info@kitchenwallapp.com
description: Introducing Kitchen Wall, a new list maker app for keeping to-do lists
  and getting stuff done with the people you love. Sharing is at the heart of what
  we do. Whether it's a grocery list, keeping up with the honey-do list, or having
  your kids manage their own chore list, Kitchen Wall is the app your whole family
  will actually use.
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
